# Generated by Django 4.2.1 on 2024-02-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='new', max_length=255)),
                ('http_status_code', models.IntegerField(default=0)),
                ('headers_from_service', models.TextField(default='')),
                ('length', models.IntegerField(default=0)),
                ('method', models.CharField(choices=[('GET', 'Get'), ('POST', 'Post')], default='GET', max_length=4)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('headers_from_client', models.TextField(blank=True)),
                ('time_create', models.DateTimeField()),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Mod',
        ),
        migrations.DeleteModel(
            name='TaskModel',
        ),
    ]
