# Generated by Django 4.2.1 on 2024-01-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='age',
            new_name='length',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_man',
        ),
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
        migrations.AddField(
            model_name='task',
            name='headers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='httpStatusCode',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
