# Generated by Django 4.2.1 on 2024-01-17 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_age_task_length_remove_task_is_man_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='httpStatusCode',
            new_name='http_status_code',
        ),
    ]
