# Generated by Django 4.2.1 on 2024-02-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_delete_mod_delete_taskmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
