# Generated by Django 4.2.1 on 2024-02-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='body_from_client',
            field=models.TextField(blank=True),
        ),
    ]
