# Generated by Django 4.2.1 on 2024-02-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_body_from_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='method',
            field=models.CharField(choices=[('GET', 'Get'), ('POST', 'Post'), ('PUT', 'Put'), ('PATCH', 'Patch'), ('DELETE', 'Delete')], default='GET', max_length=6),
        ),
    ]
