# Generated by Django 4.2.1 on 2024-02-07 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_task_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='headers_from_service',
            new_name='body_from_service',
        ),
    ]
