# Generated by Django 4.2.1 on 2024-01-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_rename_headers_task_headers_from_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='headers_from_client',
            field=models.TextField(blank=True),
        ),
    ]
