# Generated by Django 4.2.1 on 2024-01-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_task_headers_from_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='headers_from_service',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='http_status_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='new', max_length=255),
        ),
    ]
